# This is a config for E2B sandbox template.
# You can use template ID (1hfzvnmtfisi9rpqbkv4) or template name (vibe-nextjs-template-v2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-template-v2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-template-v2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-template-v2')

team_id = "6ef250f8-4aed-4f36-878c-5cb7d8b17b98"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-template-v2"
template_id = "1hfzvnmtfisi9rpqbkv4"
